# Generated by Django 2.0.7 on 2018-07-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinner_platter',
            new_name='DinnerPlatter',
        ),
    ]
