# Generated by Django 2.0.7 on 2018-07-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180731_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='price',
        ),
        migrations.AddField(
            model_name='addition',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addition',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
