# Generated by Django 2.0.7 on 2018-07-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180731_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
