# Generated by Django 2.0.7 on 2018-08-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='is_special',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='topping_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='is_special',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='topping_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
