# Generated by Django 2.0.7 on 2018-08-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
